"""Single source of truth for the OpenDA Kalman-filter configuration.

The per-filter OpenDA setup (EnKF / DEnKF / EnSR) used to be a 4-deep
chain of near-identical hand-maintained files per filter:

    <type>.oda -> parallel_<type>.xml -> simstratStochModel<Type>.xml
               -> simstratModel<Type>.xml -> simstratWrapperEnKF.xml

A diff showed the model/stochModel chain is identical across filters except the
instance (work) directory, and the only genuinely filter-specific things are the
algorithm class, its config root element/schema, and the result-writer filename —
all captured in the FILTERS spec below.

On top of that the whole setup was hardcoded to one lake: the assimilated
observation depths, the time window, and the ensemble size were baked into the
model config, the two timeSeriesFormatter files, the algorithm configs and the
wrapper.  This module renders all of it, each run, from three run inputs:

    obs_depths   - list of observation depths (auto-detected from the obs CSV)
    (start, end) - the run's date window
    n_members    - ensemble size

Generated files (all suffixed .gen so they read as build artifacts):
    run.oda                                       (openda root)
    parallel.gen.xml                              (openda root)
    stochModel/simstratStochModel.gen.xml
    stochModel/simstratModel.gen.xml
    stochObserver/timeSeriesFormatter.gen.xml     (observations + window + std)
    stochModel/template/timeSeriesFormatter.gen.xml   (model predictions)
    stochModel/template/time_control.yaml         (start/end window in Simstrat days)
    stochModel/template/obs_depths.json           (depth list the wrapper reads)
    algorithms/<filter>.gen.xml                    (full algorithm config from FILTERS)

The template's initial state file temperature_state.txt is seeded separately, by
the openda adapter (from the warmup snapshot's full-grid T profile).

Kept as-is: the wrappers and the Simstrat model template (stochModel/template/).
"""

import os
import json
from datetime import date, datetime

from alplakes_da.prep_reanalysis.config import SIMSTRAT_REF_YEAR

# Per-filter algorithm spec: OpenDA class, plus the config-file root element and
# schema (the only things that differ between filters' algorithm configs).  Add an
# "extra" string for variant body (e.g. a localized EnKF: root "EnkfConfig",
# schema "enkf.xsd", extra="\n\t<localization>Hamill</localization>\n\t<distance>10</distance>").
FILTERS = {
    "EnKF":  {"class": "org.openda.algorithms.kalmanFilter.EnKF",  "root": "EnKFConfig", "schema": "enkf.xsd"},
    "DEnKF": {"class": "org.openda.algorithms.kalmanFilter.DEnKF", "root": "EnkfConfig", "schema": "enkf.xsd"},
    "EnSR":  {"class": "org.openda.algorithms.kalmanFilter.EnSR",  "root": "EnsrConfig", "schema": "ensr.xsd"},
}

DEFAULT_OBS_STD = 0.5  # per-depth observation standard deviation (°C)


def depth_label(d):
    """'1m', '0.5m', '40m' — matches the T_<label>_real.csv / T_<label>.csv naming."""
    return f"{d:g}m"


def _simstrat_day(d):
    """Integer Simstrat day (days since 1 Jan SIMSTRAT_REF_YEAR) for a date/datetime/ISO str."""
    if isinstance(d, str):
        d = datetime.fromisoformat(d[:10])
    if isinstance(d, datetime):
        d = d.date()
    return (d - date(SIMSTRAT_REF_YEAR, 1, 1)).days


def work_dir_name(filter_type):
    """Per-filter scratch dir under run/openda/ (kept separate so the analysis
    scripts can compare filters side by side)."""
    return f"work_{filter_type.lower()}"


def results_filename(filter_type):
    return f"{filter_type.lower()}_results.py"


# --- templates -------------------------------------------------------------

_ODA = """<?xml version="1.0" encoding="UTF-8"?>
<openDaApplication xmlns="http://www.openda.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/openDaApplication.xsd">

\t<!-- GENERATED by src/alplakes_da/openda/config.py (filter={filter}). Do not edit by hand;
\t     change the FILTERS spec / templates in config.py instead. -->

\t<stochObserver className="org.openda.observers.TimeSeriesFormatterStochObserver">
\t\t<workingDirectory>./stochObserver</workingDirectory>
\t\t<configFile>timeSeriesFormatter.gen.xml</configFile>
\t</stochObserver>

\t<stochModelFactory className="org.openda.models.threadModel.ThreadStochModelFactory">
\t\t<workingDirectory>.</workingDirectory>
\t\t<configFile>parallel.gen.xml</configFile>
\t</stochModelFactory>

\t<algorithm className="{algo_class}">
\t\t<workingDirectory>./algorithms</workingDirectory>
\t\t<configString>{algo_config}</configString>
\t</algorithm>

\t<resultWriters>
\t\t<resultWriter className="org.openda.resultwriters.PythonResultWriter">
\t\t\t<workingDirectory>{results_dir}</workingDirectory>
\t\t\t<configFile>{results_file}</configFile>
\t\t\t<selection>
\t\t\t\t<!-- Verbose: stores x_f_central and x_a_central (full-grid profiles) -->
\t\t\t\t<resultItem outputLevel="Verbose" maxSize="10000000" />
\t\t\t</selection>
\t\t</resultWriter>
\t</resultWriters>

</openDaApplication>
"""

_PARALLEL = """<threadConfigstoch>
    <!-- GENERATED by src/alplakes_da/openda/config.py. maxThreads = n_members + 1 (main + ensemble). -->
    <maxThreads>{max_threads}</maxThreads>
    <stochModelFactory className="org.openda.blackbox.wrapper.BBStochModelFactory">
        <workingDirectory>./stochModel</workingDirectory>
        <configFile>simstratStochModel.gen.xml</configFile>
    </stochModelFactory>
</threadConfigstoch>
"""

_STOCHMODEL = """<?xml version="1.0" encoding="UTF-8"?>
<blackBoxStochModel xmlns="http://www.openda.org"
\txmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
\txsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxStochModelConfig.xsd">

\t<!-- GENERATED by src/alplakes_da/openda/config.py. -->

\t<modelConfig>
\t\t<file>./simstratModel.gen.xml</file>
\t</modelConfig>

\t<vectorSpecification>
\t\t<!-- Full-grid T profile — updated by the analysis step -->
\t\t<state>
\t\t\t<vector id="temperature.state" />
\t\t</state>
\t\t<!-- Predictors: model output at observation depths, matched against stochObserver -->
\t\t<predictor>
{predictors}
\t\t</predictor>
\t</vectorSpecification>

</blackBoxStochModel>
"""

_MODEL = """<?xml version="1.0" encoding="UTF-8"?>
<blackBoxModelConfig xmlns="http://www.openda.org"
\txmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
\txsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxModelConfig.xsd">

\t<!-- GENERATED by src/alplakes_da/openda/config.py (filter={filter}). -->

\t<wrapperConfig>
\t\t<file>simstratWrapperEnKF.xml</file>
\t</wrapperConfig>

\t<aliasValues>
\t\t<alias key="templateDir"  value="template" />
\t\t<alias key="instanceDir"  value="../../run/openda/{work}/work" />
\t\t<alias key="binDir"       value="bin" />
\t\t<alias key="configFile"   value="Settings.par" />
\t\t<alias key="stateFile"    value="temperature_state.txt" />
\t</aliasValues>

\t<!-- Time in Simstrat days (days since Jan 1 of reference year {ref_year}).
\t     MJD offset: Simstrat_day = MJD - 44605 -->
\t<timeInfoExchangeItems start="start_time" timeStep="time_step" end="end_time"/>

\t<exchangeItems>
\t\t<vector id="start_time"        ioObjectId="time_config" elementId="time_control@1" />
\t\t<vector id="time_step"         ioObjectId="time_config" elementId="time_control@2" />
\t\t<vector id="end_time"          ioObjectId="time_config" elementId="time_control@3" />
\t\t<vector id="temperature.state" ioObjectId="state_temperature" elementId="temperature_state" />
{outputs}
\t</exchangeItems>

\t<doCleanUp>false</doCleanUp>

</blackBoxModelConfig>
"""

# Observation formatter (stochObserver/): reads the real-obs CSVs over the window.
_OBS_FORMATTER = """<?xml version="1.0" encoding="UTF-8"?>
<timeSeriesFormatterConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- GENERATED by src/alplakes_da/openda/config.py. time column = Simstrat days (since 1 Jan {ref_year}).
       Range {start_day},{end_day} covers the configured simulation window. -->
  <formatter class="org.openda.exchange.timeseries.DelimitedTextTimeSeriesFormatter">
    <dateTimeSelector type="fixed" timeFormat="mjd">{start_day},{end_day}</dateTimeSelector>
    <valueSelector>1</valueSelector>
    <delimiter>,</delimiter>
    <commentMarker>#</commentMarker>
    <skipLines>1</skipLines>
  </formatter>
{rows}
</timeSeriesFormatterConfig>
"""

# Model-output formatter (template/): reads the predictor CSVs the wrapper writes.
_MODEL_FORMATTER = """<?xml version="1.0" encoding="UTF-8"?>
<timeSeriesFormatterConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- GENERATED by src/alplakes_da/openda/config.py. time column = Simstrat days (since 1 Jan {ref_year}). -->
  <formatter class="org.openda.exchange.timeseries.DelimitedTextTimeSeriesFormatter">
    <dateTimeSelector>0</dateTimeSelector>
    <valueSelector>1</valueSelector>
    <delimiter>,</delimiter>
    <commentMarker>#</commentMarker>
    <skipLines>1</skipLines>
  </formatter>
{rows}
</timeSeriesFormatterConfig>
"""


# Algorithm config (algorithms/): root element + schema vary per filter; the body
# (analysis at obs times, deterministic main + ensemble models, ensemble size) is shared.
_ALGORITHM = """<?xml version="1.0" encoding="UTF-8"?>
<{root} xmlns="http://www.openda.org"
\txmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
\txsi:schemaLocation="http://www.openda.org http://schemas.openda.org/algorithm/{schema}">

\t<!-- GENERATED by src/alplakes_da/openda/config.py (filter={filter}). -->

\t<analysisTimes type="fromObservationTimes" />
\t<mainModel stochParameter="false" stochForcing="false" stochInit="false" />
\t<ensembleSize>{n_members}</ensembleSize>
\t<ensembleModel stochParameter="false" stochForcing="false" stochInit="false" />{extra}
</{root}>
"""


# Model time control (template/): OpenDA reads/writes the #oda:time_control line.
_TIME_CONTROL = """%YAML 1.1
---
# GENERATED by src/alplakes_da/openda/config.py. Time in Simstrat days (days since 1 Jan {ref_year}).
# Format: [start_day, dt_day, end_day]; dt is a placeholder OpenDA overwrites each step.
time: [{start_day:.1f}, 1.0, {end_day:.1f}]  #oda:time_control
"""


def _predictor_lines(depths):
    return "\n".join(f'\t\t\t<vector id="T_{depth_label(d)}" />' for d in depths)


def _output_lines(depths):
    lines = []
    for d in depths:
        vid = f'"T_{depth_label(d)}"'
        lines.append(f'\t\t<vector id={vid:<10} ioObjectId="output" elementId="model.T_{depth_label(d)}" />')
    return "\n".join(lines)


def _obs_formatter_rows(depths, obs_std):
    return "\n".join(
        f'  <timeSeries id="T_{depth_label(d)}" status="use" standardDeviation="{obs_std}">'
        f'T_{depth_label(d)}_real.csv</timeSeries>'
        for d in depths
    )


def _model_formatter_rows(depths):
    return "\n".join(
        f'  <timeSeries id="model.T_{depth_label(d)}">T_{depth_label(d)}.csv</timeSeries>'
        for d in depths
    )


def _write(path, text, dry_run):
    if dry_run:
        print(f"  [dry-run] would write {os.path.relpath(path)}")
        return
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def render(openda_dir, filter_type, n_members, obs_depths, start_date, end_date,
           obs_std=DEFAULT_OBS_STD, results_subdir=".", dry_run=False):
    """Render the full lake-specific OpenDA config for `filter_type` into `openda_dir`.

    `obs_depths` is the list of assimilated depths (e.g. auto-detected from the obs
    CSV); it drives the model exchangeItems, the stochModel predictors, both
    timeSeriesFormatter files and the wrapper's depth list.  Returns the .oda
    filename (relative to openda_dir) to hand to oda_run.sh.
    """
    if filter_type not in FILTERS:
        raise ValueError(f"unknown filter '{filter_type}'; choose from {sorted(FILTERS)}")
    if not obs_depths:
        raise ValueError("obs_depths is empty — no observations to assimilate")
    spec = FILTERS[filter_type]
    depths = sorted(obs_depths)

    stoch_dir    = os.path.join(openda_dir, "stochModel")
    template_dir = os.path.join(stoch_dir, "template")
    obs_cfg_dir  = os.path.join(openda_dir, "stochObserver")
    algo_dir     = os.path.join(openda_dir, "algorithms")
    for d in (stoch_dir, template_dir, obs_cfg_dir, algo_dir):
        if not os.path.isdir(d):
            raise FileNotFoundError(f"expected OpenDA dir not found: {d}")

    algo_file = f"{filter_type}.gen.xml"
    start_day, end_day = _simstrat_day(start_date), _simstrat_day(end_date) + 1

    oda = _ODA.format(
        filter=filter_type, algo_class=spec["class"], algo_config=algo_file,
        results_dir=results_subdir, results_file=results_filename(filter_type),
    )
    parallel   = _PARALLEL.format(max_threads=n_members + 1)
    stochmodel = _STOCHMODEL.format(predictors=_predictor_lines(depths))
    model      = _MODEL.format(filter=filter_type, work=work_dir_name(filter_type),
                               ref_year=SIMSTRAT_REF_YEAR, outputs=_output_lines(depths))
    obs_fmt    = _OBS_FORMATTER.format(ref_year=SIMSTRAT_REF_YEAR, start_day=start_day,
                                       end_day=end_day, rows=_obs_formatter_rows(depths, obs_std))
    model_fmt  = _MODEL_FORMATTER.format(ref_year=SIMSTRAT_REF_YEAR, rows=_model_formatter_rows(depths))
    time_ctrl  = _TIME_CONTROL.format(ref_year=SIMSTRAT_REF_YEAR, start_day=start_day, end_day=end_day)
    algo_cfg   = _ALGORITHM.format(root=spec["root"], schema=spec["schema"], filter=filter_type,
                                   n_members=n_members, extra=spec.get("extra", ""))

    _write(os.path.join(openda_dir, "run.oda"), oda, dry_run)
    _write(os.path.join(openda_dir, "parallel.gen.xml"), parallel, dry_run)
    _write(os.path.join(stoch_dir, "simstratStochModel.gen.xml"), stochmodel, dry_run)
    _write(os.path.join(stoch_dir, "simstratModel.gen.xml"), model, dry_run)
    _write(os.path.join(obs_cfg_dir, "timeSeriesFormatter.gen.xml"), obs_fmt, dry_run)
    _write(os.path.join(template_dir, "timeSeriesFormatter.gen.xml"), model_fmt, dry_run)
    _write(os.path.join(template_dir, "time_control.yaml"), time_ctrl, dry_run)
    _write(os.path.join(template_dir, "obs_depths.json"), json.dumps(depths), dry_run)
    _write(os.path.join(algo_dir, algo_file), algo_cfg, dry_run)
    return "run.oda"
